"""Rename description to caption

Revision ID: 58ac7bba3be0
Revises: 1a31ce608336
Create Date: 2025-06-06 15:55:39.398822

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '58ac7bba3be0'
down_revision = '1a31ce608336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('caption', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('item', sa.Column('hashtags', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('item', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('item', 'hashtags')
    op.drop_column('item', 'caption')
    # ### end Alembic commands ###
